name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: |
          cd demo  # Переход в директорию с pom.xml
          mvn -B package --file pom.xml  # Выполнение Maven в директории demo

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change directory to 'demo'
        run: cd demo  

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 myapp:latest
